export const DEFAULT_DDC_WRITE_THROTTLE_MS = 500;
export const DEFAULT_ENFORCEMENT_DURATION_MS = 10000;
export const DEFAULT_ENFORCEMENT_INTERVAL_MS = 500;
export const DEFAULT_POLL_INTERVAL_MS = 3000;
