export const DEFAULT_DDC_WRITE_THROTTLE_MS = 1000;
export const DEFAULT_ENFORCEMENT_DURATION_MS = 10000;
export const DEFAULT_ENFORCEMENT_INTERVAL_MS = 1000;
export const DEFAULT_BRIGHTNESS_POLL_INTERVAL_MS = 3000;
export const DEFAULT_MONITOR_POLL_INTERVAL_MS = 10000;
